repos:
  - repo: https://github.com/gozynta/pre-commit-hooks
    rev: "v1.0.0"
    hooks:
      - id: check-poetry-sources
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: pretty-format-json
        args:
          - "--autofix"
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
      - id: check-merge-conflict
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args:
          - "--py310-plus"
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      - id: ruff
        args:
          - "--fix"
          - "--exit-non-zero-on-fix"
  - repo: https://github.com/andrei-shabanski/poetry-plugin-sort
    rev: v0.2.1
    hooks:
      - id: poetry-sort
  - repo: https://github.com/python-poetry/poetry
    rev: "2.1.1"
    hooks:
      - id: poetry-check

ci:
  autofix_prs: true
  autofix_commit_msg: "[pre-commit.ci] automatic pre-commit fixes"
