# generated by datamodel-codegen:
#   filename:  All.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from .. import CampaignTypeReference


class CampaignSubType(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int | None = None
    type: CampaignTypeReference | None = None
    name: str
    """
     Max length: 100;
    """
    field_info: dict[str, str] | None = Field(default=None, alias='_info')
