# generated by datamodel-codegen:
#   filename:  All.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class CampaignSubType(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int | None = None
    type_id: int | None = Field(default=None, alias='typeId')
    name: str | None = None
    field_info: dict[str, str] | None = Field(default=None, alias='_info')
