# generated by datamodel-codegen:
#   filename:  All.json

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field

from . import CustomFieldValue


class Adjustment(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int | None = None
    amount: float | None = None
    description: str | None = None
    """
     Max length: 1000;
    """
    effective_date: datetime | None = Field(default=None, alias='effectiveDate')
    agreement_id: int | None = Field(default=None, alias='agreementId')
    field_info: dict[str, str] | None = Field(default=None, alias='_info')
    custom_fields: list[CustomFieldValue] | None = Field(
        default=None, alias='customFields'
    )
