# generated by datamodel-codegen:
#   filename:  All.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import CompanyReference, CompanyTypeReference


class CompanyTypeAssociation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int | None = None
    type: CompanyTypeReference | None = None
    company: CompanyReference | None = None
    field_info: dict[str, str] | None = Field(default=None, alias='_info')
