# generated by datamodel-codegen:
#   filename:  All.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import ContactReference, ContactTypeReference


class ContactTypeAssociation(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: int | None = None
    type: ContactTypeReference | None = None
    contact: ContactReference | None = None
    field_info: dict[str, str] | None = Field(default=None, alias='_info')
